//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 

public class source { 
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nav.gov.hu/2013/szamla")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.nav.gov.hu/2013/szamla", IsNullable=false)]
public partial class cim {
    
    private string iranyitoszamField;
    
    private string telepulesField;
    
    private string kozterulet_neveField;
    
    /// <remarks/>
    public string iranyitoszam {
        get {
            return this.iranyitoszamField;
        }
        set {
            this.iranyitoszamField = value;
        }
    }
    
    /// <remarks/>
    public string telepules {
        get {
            return this.telepulesField;
        }
        set {
            this.telepulesField = value;
        }
    }
    
    /// <remarks/>
    public string kozterulet_neve {
        get {
            return this.kozterulet_neveField;
        }
        set {
            this.kozterulet_neveField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nav.gov.hu/2013/szamla")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.nav.gov.hu/2013/szamla", IsNullable=false)]
public partial class szamlak {
    
    private string export_datumaField;
    
    private string export_szla_dbField;
    
    private string kezdo_idoField;
    
    private string zaro_idoField;
    
    private string kezdo_szla_szamField;
    
    private string zaro_szla_szamField;
    
    private szamlakSzamla[] szamlaField;
    
    /// <remarks/>
    public string export_datuma {
        get {
            return this.export_datumaField;
        }
        set {
            this.export_datumaField = value;
        }
    }
    
    /// <remarks/>
    public string export_szla_db {
        get {
            return this.export_szla_dbField;
        }
        set {
            this.export_szla_dbField = value;
        }
    }
    
    /// <remarks/>
    public string kezdo_ido {
        get {
            return this.kezdo_idoField;
        }
        set {
            this.kezdo_idoField = value;
        }
    }
    
    /// <remarks/>
    public string zaro_ido {
        get {
            return this.zaro_idoField;
        }
        set {
            this.zaro_idoField = value;
        }
    }
    
    /// <remarks/>
    public string kezdo_szla_szam {
        get {
            return this.kezdo_szla_szamField;
        }
        set {
            this.kezdo_szla_szamField = value;
        }
    }
    
    /// <remarks/>
    public string zaro_szla_szam {
        get {
            return this.zaro_szla_szamField;
        }
        set {
            this.zaro_szla_szamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("szamla")]
    public szamlakSzamla[] szamla {
        get {
            return this.szamlaField;
        }
        set {
            this.szamlaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nav.gov.hu/2013/szamla")]
public partial class szamlakSzamla {
    
    private szamlakSzamlaFejlec[] fejlecField;
    
    private szamlakSzamlaSzamlakibocsato[] szamlakibocsatoField;
    
    private szamlakSzamlaVevo[] vevoField;
    
    private szamlakSzamlaTermek_szolgaltatas_tetelek[] termek_szolgaltatas_tetelekField;
    
    private szamlakSzamlaModosito_szla[] modosito_szlaField;
    
    private szamlakSzamlaNem_kotelezo[] nem_kotelezoField;
    
    private szamlakSzamlaOsszesitesVegosszeg[][] osszesitesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fejlec")]
    public szamlakSzamlaFejlec[] fejlec {
        get {
            return this.fejlecField;
        }
        set {
            this.fejlecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("szamlakibocsato")]
    public szamlakSzamlaSzamlakibocsato[] szamlakibocsato {
        get {
            return this.szamlakibocsatoField;
        }
        set {
            this.szamlakibocsatoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("vevo")]
    public szamlakSzamlaVevo[] vevo {
        get {
            return this.vevoField;
        }
        set {
            this.vevoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("termek_szolgaltatas_tetelek")]
    public szamlakSzamlaTermek_szolgaltatas_tetelek[] termek_szolgaltatas_tetelek {
        get {
            return this.termek_szolgaltatas_tetelekField;
        }
        set {
            this.termek_szolgaltatas_tetelekField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("modosito_szla")]
    public szamlakSzamlaModosito_szla[] modosito_szla {
        get {
            return this.modosito_szlaField;
        }
        set {
            this.modosito_szlaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("nem_kotelezo")]
    public szamlakSzamlaNem_kotelezo[] nem_kotelezo {
        get {
            return this.nem_kotelezoField;
        }
        set {
            this.nem_kotelezoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("vegosszeg", typeof(szamlakSzamlaOsszesitesVegosszeg), IsNullable=false)]
    public szamlakSzamlaOsszesitesVegosszeg[][] osszesites {
        get {
            return this.osszesitesField;
        }
        set {
            this.osszesitesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nav.gov.hu/2013/szamla")]
public partial class szamlakSzamlaFejlec {
    
    private string szlasorszamField;
    
    private string szlatipusField;
    
    private string szladatumField;
    
    private string teljdatumField;
    
    /// <remarks/>
    public string szlasorszam {
        get {
            return this.szlasorszamField;
        }
        set {
            this.szlasorszamField = value;
        }
    }
    
    /// <remarks/>
    public string szlatipus {
        get {
            return this.szlatipusField;
        }
        set {
            this.szlatipusField = value;
        }
    }
    
    /// <remarks/>
    public string szladatum {
        get {
            return this.szladatumField;
        }
        set {
            this.szladatumField = value;
        }
    }
    
    /// <remarks/>
    public string teljdatum {
        get {
            return this.teljdatumField;
        }
        set {
            this.teljdatumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nav.gov.hu/2013/szamla")]
public partial class szamlakSzamlaSzamlakibocsato {
    
    private string adoszamField;
    
    private string nevField;
    
    private cim[] cimField;
    
    /// <remarks/>
    public string adoszam {
        get {
            return this.adoszamField;
        }
        set {
            this.adoszamField = value;
        }
    }
    
    /// <remarks/>
    public string nev {
        get {
            return this.nevField;
        }
        set {
            this.nevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cim")]
    public cim[] cim {
        get {
            return this.cimField;
        }
        set {
            this.cimField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nav.gov.hu/2013/szamla")]
public partial class szamlakSzamlaVevo {
    
    private string adoszamField;
    
    private string nevField;
    
    private cim[] cimField;
    
    /// <remarks/>
    public string adoszam {
        get {
            return this.adoszamField;
        }
        set {
            this.adoszamField = value;
        }
    }
    
    /// <remarks/>
    public string nev {
        get {
            return this.nevField;
        }
        set {
            this.nevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cim")]
    public cim[] cim {
        get {
            return this.cimField;
        }
        set {
            this.cimField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nav.gov.hu/2013/szamla")]
public partial class szamlakSzamlaTermek_szolgaltatas_tetelek {
    
    private string termeknevField;
    
    private string mennyField;
    
    private string mertekegysField;
    
    private string nettoarField;
    
    private string nettoegysarField;
    
    private string adokulcsField;
    
    private string adoertekField;
    
    /// <remarks/>
    public string termeknev {
        get {
            return this.termeknevField;
        }
        set {
            this.termeknevField = value;
        }
    }
    
    /// <remarks/>
    public string menny {
        get {
            return this.mennyField;
        }
        set {
            this.mennyField = value;
        }
    }
    
    /// <remarks/>
    public string mertekegys {
        get {
            return this.mertekegysField;
        }
        set {
            this.mertekegysField = value;
        }
    }
    
    /// <remarks/>
    public string nettoar {
        get {
            return this.nettoarField;
        }
        set {
            this.nettoarField = value;
        }
    }
    
    /// <remarks/>
    public string nettoegysar {
        get {
            return this.nettoegysarField;
        }
        set {
            this.nettoegysarField = value;
        }
    }
    
    /// <remarks/>
    public string adokulcs {
        get {
            return this.adokulcsField;
        }
        set {
            this.adokulcsField = value;
        }
    }
    
    /// <remarks/>
    public string adoertek {
        get {
            return this.adoertekField;
        }
        set {
            this.adoertekField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nav.gov.hu/2013/szamla")]
public partial class szamlakSzamlaModosito_szla {
    
    private string eredeti_sorszamField;
    
    /// <remarks/>
    public string eredeti_sorszam {
        get {
            return this.eredeti_sorszamField;
        }
        set {
            this.eredeti_sorszamField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nav.gov.hu/2013/szamla")]
public partial class szamlakSzamlaNem_kotelezo {
    
    private string penznemField;
    
    /// <remarks/>
    public string penznem {
        get {
            return this.penznemField;
        }
        set {
            this.penznemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nav.gov.hu/2013/szamla")]
public partial class szamlakSzamlaOsszesitesVegosszeg {
    
    private string nettoarosszField;
    
    private string afaertekosszField;
    
    private string bruttoarosszField;
    
    /// <remarks/>
    public string nettoarossz {
        get {
            return this.nettoarosszField;
        }
        set {
            this.nettoarosszField = value;
        }
    }
    
    /// <remarks/>
    public string afaertekossz {
        get {
            return this.afaertekosszField;
        }
        set {
            this.afaertekosszField = value;
        }
    }
    
    /// <remarks/>
    public string bruttoarossz {
        get {
            return this.bruttoarosszField;
        }
        set {
            this.bruttoarosszField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.nav.gov.hu/2013/szamla")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.nav.gov.hu/2013/szamla", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cim", typeof(cim))]
    [System.Xml.Serialization.XmlElementAttribute("szamlak", typeof(szamlak))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
}